service: serverless
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:GetItem"
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
functions:
  create:
    handler: handler.create
    events:
      - http:
          path: transaction/create
          method: post
          authorizer: authorizerFunc
          cors: true
  list:
    handler: handler.list
    events:
      - http:
          path: transaction/list
          method: get
          authorizer: authorizerFunc
          cors: true
  get:
    handler: handler.get
    events:
      - http:
          path: transaction/{id}
          method: get
          authorizer: authorizerFunc
          cors: true
  authorizerFunc:
    handler: authorizer.handler