service: transaction
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
        - "dynamodb:GetItem"
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
functions:
  create:
    handler: ./lib/transaction/handler.create
    events:
      - http:
          path: transaction/create
          method: post
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:713776634223:userpool/us-east-1_1LUK6tUjp
          cors: true
  list:
    handler: ./lib/transaction/handler.list
    events:
      - http:
          path: transaction/list
          method: get
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:713776634223:userpool/us-east-1_1LUK6tUjp
          cors: true
  get:
    handler: ./lib/handler.get
    events:
      - http:
          path: transaction/{id}
          method: get
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:713776634223:userpool/us-east-1_1LUK6tUjp
          cors: true
